sequenceDiagram
  autonumber
  actor PMO as PMO / планировщик
  participant PS as Planning System
  participant HR as HR-система
  participant TT as Task Tracker
  participant FS as Финансовая система
  actor RM as Ресурсный руководитель
  actor FC as Финансовый контролер
  actor SP as Спонсор

  PMO->>PS: Создать годовой сценарий портфеля
  PS->>HR: Получить оргструктуру, календари и мощности
  HR-->>PS: Актуальные данные с датой среза
  PS->>TT: Получить незавершенные работы и факт
  TT-->>PS: Задачи, прогресс, трудозатраты
  PS->>FS: Получить лимиты, обязательства и факт
  FS-->>PS: Финансовый срез
  PS->>PS: Рассчитать сроки, потребность, стоимость и дефициты
  PS-->>PMO: Сравнение сценариев и предупреждения
  PMO->>RM: Направить ресурсную часть на согласование
  RM-->>PS: Подтвердить мощности / вернуть замечания
  PMO->>FC: Направить бюджет на согласование
  FC-->>PS: Подтвердить источники / вернуть замечания
  PMO->>SP: Направить целевой сценарий
  SP-->>PS: Утвердить план
  PS->>PS: Зафиксировать неизменяемую базовую линию
  PS-->>TT: Опубликовать утвержденные плановые рамки
