// Package healthv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package healthv1

// FailedDependency defines model for FailedDependency.
type FailedDependency struct {
	// Error The error message or reason for the dependency failure.
	Error string `json:"error"`

	// Name The name of the failed dependency (e.g., Database, Cache, External API).
	Name string `json:"name"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	// FailedDependencies A list of internal or external systems that are currently unreachable or failing.
	FailedDependencies []FailedDependency `json:"failedDependencies"`

	// Ready Indicates whether the service is fully operational.
	Ready bool `json:"ready"`
}
