// Package healthv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package healthv1

// Readiness Result of the service readiness check.
type Readiness struct {
	// FailedDependencies List of dependencies that failed the readiness check.
	//
	// The list is empty when the service is ready.
	FailedDependencies []struct {
		// Error Description of the readiness check failure.
		//
		// Example: connection refused
		Error string `json:"error"`

		// Name Name of the failed dependency.
		//
		// Example: postgres
		Name string `json:"name"`
	} `json:"failedDependencies"`

	// Ready Indicates whether the service is ready to handle requests.
	//
	// Example: true
	Ready bool `json:"ready"`
}
