import React, { useCallback, useEffect, useState } from 'react';
import { auth, date, dateTime, hours, json, request, typeName } from './api';
import type { Item, Iteration, Json, Priority, Status, User } from './api';
import { compareAssignee } from './metrics';

type Screen = 'backlog' | 'board' | 'iterations' | 'notifications' | 'admin';
type Context = { statuses: Status[]; priorities: Priority[]; users: User[]; role: string; userId: string; permissions: string[]; types: Array<{ type: string; enabled: boolean }> };
type Page<T> = { items: T[]; page: number; pageSize: number; totalPages: number; total: number };
const emptyContext: Context = { statuses: [], priorities: [], users: [], role: '', userId: '', permissions: [], types: [] };
const can = (context: Context, permission: string) => context.permissions.includes(permission);
const iso = (value: unknown) => value ? String(value).slice(0, 10) : '';
const getError = (e: unknown) => e instanceof Error ? e.message : 'Неизвестная ошибка';
const selectName = (rows: Array<{ id: string; name: string }>, id: string | null) => rows.find(row => row.id === id)?.name || '—';

export function App() {
  const [ready, setReady] = useState(false);
  const [context, setContext] = useState<Context>(emptyContext);
  const [screen, setScreen] = useState<Screen>('backlog');
  const [selected, setSelected] = useState<string | null>(null);
  const [revision, setRevision] = useState(0);
  const [error, setError] = useState('');
  const refresh = useCallback(() => setRevision(value => value + 1), []);
  const reloadContext = useCallback(async () => {
    const [me, statuses, priorities, users, types] = await Promise.all([
      request<{ role: string; userId: string; permissions: string[] }>('/me'), request<Status[]>('/statuses'),
      request<Priority[]>('/priorities'), request<User[]>('/users'), request<Context['types']>('/types'),
    ]);
    setContext({ ...me, statuses, priorities, users, types });
  }, []);
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        if (location.pathname === '/auth/callback') {
          await auth.signinRedirectCallback();
          history.replaceState({}, '', '/');
        }
        const user = await auth.getUser();
        if (!user || user.expired) { await auth.signinRedirect(); return; }
        await reloadContext();
        if (!cancelled) setReady(true);
      } catch (e) { if (!cancelled) setError(getError(e)); }
    })();
    return () => { cancelled = true; };
  }, [reloadContext]);
  if (!ready) return <main className="startup"><div className="spinner"/><h1>Task Tracker</h1><p>{error || 'Загрузка рабочего пространства…'}</p>{error && <button onClick={() => void auth.signinRedirect()}>Войти снова</button>}</main>;
  const titles: Record<Screen, string> = { backlog: 'Бэклог', board: 'Канбан-доска', iterations: 'Итерации', notifications: 'Уведомления', admin: 'Администрирование' };
  const nav: Array<[Screen, string]> = [['backlog','▤'],['board','▥'],['iterations','◷'],['notifications','◉'],['admin','⚙']];
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-icon">T</span><div><strong>Task Tracker</strong><small>Рабочее пространство</small></div></div>
      <nav aria-label="Основная навигация">{nav.filter(([key]) => key === 'admin' ? ['access.admin','status.admin','priority.admin','type.admin','directory.admin'].some(permission => can(context,permission)) : key === 'iterations' ? can(context,'iteration.read') : key === 'notifications' ? can(context,'notifications.read') : can(context,'item.read')).map(([key, icon]) =>
        <button key={key} className={`nav-link ${screen === key ? 'active' : ''}`} onClick={() => { setScreen(key); setSelected(null); }}><span>{icon}</span>{titles[key]}</button>)}</nav>
      <div className="sidebar-footer"><div className="avatar">{context.role.charAt(0)}</div><div><strong>{selectName(context.users, context.userId)}</strong><small>{context.role}</small></div><button title="Выйти" onClick={() => void auth.signoutRedirect()}>↗</button></div>
    </aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">КОМАНДНАЯ РАБОТА</span><h1>{titles[screen]}</h1></div><span className="today">{date(new Date().toISOString())}</span></header>
      {screen === 'backlog' && <Backlog context={context} revision={revision} open={setSelected} refresh={refresh} />}
      {screen === 'board' && <Board context={context} revision={revision} open={setSelected} refresh={refresh} />}
      {screen === 'iterations' && <Iterations context={context} revision={revision} open={setSelected} refresh={refresh} />}
      {screen === 'notifications' && <Notifications open={setSelected} revision={revision} refresh={refresh} />}
      {screen === 'admin' && <Admin context={context} refreshAll={() => { void reloadContext(); refresh(); }} />}
    </main>
    {selected && <ItemDialog id={selected} context={context} close={() => setSelected(null)} open={setSelected} refresh={refresh} />}
  </div>;
}

function ErrorBanner({ message, clear }: { message: string; clear?: () => void }) { return message ? <div className="error-banner" role="alert"><span>{message}</span>{clear && <button onClick={clear}>Закрыть</button>}</div> : null; }
function Empty({ text }: { text: string }) { return <div className="empty"><span>◌</span><p>{text}</p></div>; }
function Badge({ children, tone = '' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }

function Backlog({ context, revision, open, refresh }: { context: Context; revision: number; open: (id: string) => void; refresh: () => void }) {
  const [page, setPage] = useState<Page<Item> | null>(null);
  const [filters, setFilters] = useState({ search: '', type: '', statusId: '', priorityId: '', assigneeId: '', iterationId: '', sort: 'dueDate' });
  const [iterations, setIterations] = useState<Iteration[]>([]);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    let active = true; setLoading(true);
    const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value));
    Promise.all([request<Page<Item>>(`/work-items?${query}`), request<Iteration[]>('/iterations')]).then(([result, all]) => { if (active) { setPage(result); setIterations(all); setLoading(false); } }).catch(e => { if (active) { setError(getError(e)); setLoading(false); } });
    return () => { active = false; };
  }, [filters, revision]);
  const change = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value }));
  const exportFile = async () => {
    try { const blob = await request<Blob>('/exports/work-items', json('POST', {})); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'task-tracker.xlsx'; a.click(); URL.revokeObjectURL(url); }
    catch (e) { setError(getError(e)); }
  };
  const importFile = async (file: File) => {
    try { const form = new FormData(); form.append('file', file); const result = await request<{ created: number; updated: number; rejected: number; errors: Json[] }>('/imports/work-items', { method: 'POST', body: form }); alert(`Создано: ${result.created}, обновлено: ${result.updated}, отклонено: ${result.rejected}`); refresh(); }
    catch (e) { setError(getError(e)); }
  };
  return <section className="screen-content"><div className="section-heading"><div><h2>Все рабочие элементы</h2><p>Планируйте, назначайте и отслеживайте работу команды</p></div><div className="actions">
    {can(context,'excel.export') && <button className="button secondary" onClick={() => void exportFile()}>↓ Экспорт .xlsx</button>}{can(context,'excel.import') && <label className="button secondary file-button">↑ Импорт .xlsx<input type="file" accept=".xlsx" onChange={e => { const file = e.target.files?.[0]; if (file) void importFile(file); e.target.value = ''; }}/></label>}
    {can(context,'item.create') && <button className="button primary" onClick={() => setCreating(true)}>＋ Создать элемент</button>}
  </div></div>
    <ErrorBanner message={error} clear={() => setError('')}/>
    <div className="filters"><input aria-label="Поиск" placeholder="Поиск по названию" value={filters.search} onChange={e => change('search', e.target.value)}/>
      <select aria-label="Тип" value={filters.type} onChange={e => change('type',e.target.value)}><option value="">Все типы</option>{context.types.map(row => <option key={row.type} value={row.type}>{typeName(row.type)}</option>)}</select>
      <select aria-label="Статус" value={filters.statusId} onChange={e => change('statusId',e.target.value)}><option value="">Все статусы</option>{context.statuses.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>
      <select aria-label="Приоритет" value={filters.priorityId} onChange={e => change('priorityId',e.target.value)}><option value="">Все приоритеты</option>{context.priorities.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>
      <select aria-label="Исполнитель" value={filters.assigneeId} onChange={e => change('assigneeId',e.target.value)}><option value="">Все исполнители</option>{context.users.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>
      <select aria-label="Итерация" value={filters.iterationId} onChange={e => change('iterationId',e.target.value)}><option value="">Все итерации</option>{iterations.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>
      <select aria-label="Сортировка" value={filters.sort} onChange={e => change('sort',e.target.value)}><option value="dueDate">По сроку</option><option value="priority">По приоритету</option><option value="status">По статусу</option><option value="createdAt">Сначала новые</option></select>
    </div>
    <div className="panel table-panel">{loading ? <p className="loading">Загрузка элементов…</p> : page?.items.length ? <div className="table-scroll"><table><thead><tr><th>Элемент</th><th>Тип</th><th>Статус</th><th>Приоритет</th><th>Исполнитель</th><th>Срок</th><th>План / Факт / Остаток</th></tr></thead><tbody>{page.items.map(item => <tr key={item.id} onClick={() => open(item.id)} tabIndex={0} onKeyDown={e => { if (e.key === 'Enter') open(item.id); }}><td><strong>{item.title}</strong><small>{item.id.slice(0, 8)}</small></td><td>{typeName(item.type)}</td><td><Badge tone={context.statuses.find(row => row.id === item.statusId)?.category === 'COMPLETED' ? 'green' : ''}>{selectName(context.statuses,item.statusId)}</Badge></td><td>{selectName(context.priorities,item.priorityId)}</td><td>{selectName(context.users,item.assigneeId)}</td><td>{item.dueDate ? date(item.dueDate) : '—'}</td><td className={item.remainingHours < 0 ? 'negative' : ''}>{hours(item.plannedHours)} / {hours(item.actualHours)} / {hours(item.remainingHours)}</td></tr>)}</tbody></table></div> : <Empty text="По выбранным фильтрам рабочих элементов нет"/>}</div>
    {page && <p className="list-foot">Всего элементов: {page.total}</p>}
    {creating && <CreateItem context={context} close={() => setCreating(false)} created={id => { setCreating(false); refresh(); open(id); }}/>}</section>;
}

function CreateItem({ context, close, created, parentId, suggestedType }: { context: Context; close: () => void; created: (id: string) => void; parentId?: string; suggestedType?: string }) {
  const [form, setForm] = useState({ type: suggestedType || 'TASK', title: '', description: '', priorityId: context.priorities.find(p => p.active && p.code === 'medium')?.id || '', assigneeId: '', startDate: '', dueDate: '', plannedHours: '', parentId: parentId || '' });
  const [error, setError] = useState('');
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { const body = { ...form, assigneeId: form.assigneeId || null, parentId: form.parentId || null, plannedHours: form.plannedHours || null, startDate: form.startDate || null, dueDate: form.dueDate || null }; const item = await request<Item>('/work-items',json('POST',body)); created(item.id); } catch (e) { setError(getError(e)); } };
  return <div className="overlay" onMouseDown={close}><div className="small-dialog" role="dialog" aria-modal="true" aria-label="Новый рабочий элемент" onMouseDown={e => e.stopPropagation()}><div className="dialog-title"><h2>Новый рабочий элемент</h2><button onClick={close} aria-label="Закрыть">×</button></div><form onSubmit={e => void save(e)} className="form-grid"><ErrorBanner message={error}/><label>Тип<select value={form.type} onChange={e => set('type',e.target.value)}>{context.types.filter(row => row.enabled).map(row => <option key={row.type} value={row.type}>{typeName(row.type)}</option>)}</select></label><label>Название<input required value={form.title} onChange={e => set('title',e.target.value)}/></label><label className="span-2">Описание<textarea rows={3} value={form.description} onChange={e => set('description',e.target.value)}/></label><label>Приоритет<select value={form.priorityId} onChange={e => set('priorityId',e.target.value)}>{context.priorities.filter(row => row.active).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Исполнитель<select value={form.assigneeId} onChange={e => set('assigneeId',e.target.value)}><option value="">Не назначен</option>{context.users.filter(row => row.active).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Начало<input type="date" value={form.startDate} onChange={e => set('startDate',e.target.value)}/></label><label>Срок<input type="date" value={form.dueDate} onChange={e => set('dueDate',e.target.value)}/></label><label>План, ч<input type="number" min="0" step="0.01" value={form.plannedHours} onChange={e => set('plannedHours',e.target.value)}/></label><label>Родительский ID<input value={form.parentId} onChange={e => set('parentId',e.target.value)}/></label><div className="dialog-actions span-2"><button type="button" className="button secondary" onClick={close}>Отмена</button><button className="button primary" type="submit">Создать</button></div></form></div></div>;
}

function Board({ context, revision, open, refresh }: { context: Context; revision: number; open: (id: string) => void; refresh: () => void }) {
  const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ assigneeId: '', priorityId: '', iterationId: '' });
  const [iterations, setIterations] = useState<Iteration[]>([]);
  useEffect(() => { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); Promise.all([request<Page<Item>>(`/work-items?pageSize=500&${query}`),request<Iteration[]>('/iterations')]).then(([page, all]) => { setItems(page.items.filter(item => ['TASK','BUG','SUBTASK'].includes(item.type))); setIterations(all); }).catch(e => setError(getError(e))); }, [filters, revision]);
  const move = async (id: string, statusId: string) => { if(!can(context,'item.status'))return;try { const item = items.find(row => row.id === id); await request(`/work-items/${id}`,json('PATCH',{ statusId, version: item?.version })); refresh(); } catch(e){ setError(getError(e)); refresh(); } };
  const columns = context.statuses.filter(status => status.active && status.boardVisible).sort((a,b) => a.boardOrder-b.boardOrder);
  return <section className="screen-content"><div className="section-heading"><div><h2>Поток работы</h2><p>Перемещайте карточки между колонками</p></div></div><ErrorBanner message={error} clear={() => setError('')}/><div className="filters compact"><select value={filters.assigneeId} onChange={e => setFilters(v => ({...v,assigneeId:e.target.value}))}><option value="">Все исполнители</option>{context.users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={filters.priorityId} onChange={e => setFilters(v => ({...v,priorityId:e.target.value}))}><option value="">Все приоритеты</option>{context.priorities.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={filters.iterationId} onChange={e => setFilters(v => ({...v,iterationId:e.target.value}))}><option value="">Все итерации</option>{iterations.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select></div>
    {columns.length ? <div className="board">{columns.map((status, index) => <div className="board-column" key={status.id} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const id = e.dataTransfer.getData('text/plain'); if(id) void move(id,status.id); }}><div className="column-head"><strong>{status.name}</strong><span>{items.filter(item => item.statusId === status.id).length}</span></div>{items.filter(item => item.statusId === status.id).map(item => <div key={item.id} className="board-card" draggable={can(context,'item.status')&&can(context,'item.update')} onDragStart={e => e.dataTransfer.setData('text/plain',item.id)} tabIndex={0} onKeyDown={e => { if(e.key === 'Enter')open(item.id); if(e.key === 'ArrowRight' && columns[index+1])void move(item.id,columns[index+1].id); if(e.key === 'ArrowLeft' && columns[index-1])void move(item.id,columns[index-1].id); }} onClick={() => open(item.id)}><div className="card-top"><small>{typeName(item.type)} · {item.id.slice(0,8)}</small><span>⋮</span></div><strong>{item.title}</strong><div className="card-bottom"><span>{selectName(context.users,item.assigneeId)}</span><Badge>{selectName(context.priorities,item.priorityId)}</Badge></div><div className="card-bottom"><small>{item.dueDate ? date(item.dueDate) : 'Без срока'}</small><small className={item.remainingHours<0?'negative':''}>{hours(item.remainingHours)}</small></div></div>)}</div>)}</div> : <Empty text="Активных колонок пока нет"/>}</section>;
}

function ItemDialog({ id, context, close, open, refresh }: { id: string; context: Context; close: () => void; open: (id: string) => void; refresh: () => void }) {
  const [item, setItem] = useState<Item | null>(null);
  const [form, setForm] = useState<Json>({});
  const [comments, setComments] = useState<Array<Json>>([]);
  const [logs, setLogs] = useState<Array<Json>>([]);
  const [attachments, setAttachments] = useState<Array<Json>>([]);
  const [preview, setPreview] = useState<{ name: string; url: string; type: string } | null>(null);
  const [history, setHistory] = useState<Array<Json>>([]);
  const [tab, setTab] = useState<'discussion'|'time'|'files'|'history'>('discussion');
  const [error, setError] = useState('');
  const [comment, setComment] = useState('');
  const [logHours, setLogHours] = useState('');
  const [logDate, setLogDate] = useState(new Date().toISOString().slice(0, 10));
  const [childForm, setChildForm] = useState(false);
  const load = useCallback(async () => {
    try {
      const [data, discussion, time, files, audit] = await Promise.all([
        request<Item>(`/work-items/${id}`), request<Array<Json>>(`/work-items/${id}/comments`),
        request<Array<Json>>(`/work-items/${id}/time-logs`), request<Array<Json>>(`/work-items/${id}/attachments`),
        request<Array<Json>>(`/work-items/${id}/history`),
      ]);
      setItem(data); setComments(discussion); setLogs(time); setAttachments(files); setHistory(audit);
      const draft = localStorage.getItem(`description:${id}`);
      setForm({ title: data.title, description: draft ?? data.description, statusId: data.statusId, priorityId: data.priorityId, assigneeId: data.assigneeId || '', startDate: iso(data.startDate), dueDate: iso(data.dueDate), plannedHours: data.children.length || ['PROJECT','EPIC'].includes(data.type) ? '' : String(data.plannedHours), parentId: data.parentId || '' });
    } catch (e) { setError(getError(e)); }
  }, [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => () => { if(preview)URL.revokeObjectURL(preview.url); }, [preview]);
  useEffect(() => { const listener = (e: KeyboardEvent) => { if(e.key === 'Escape')close(); }; window.addEventListener('keydown',listener); return () => window.removeEventListener('keydown',listener); }, [close]);
  const set = (key: string, value: unknown) => { setForm(current => ({ ...current, [key]: value })); if(key === 'description')localStorage.setItem(`description:${id}`,String(value)); };
  const save = async () => { if(!item)return;try { await request(`/work-items/${id}`,json('PATCH',{ ...form, assigneeId: form.assigneeId || null, parentId: form.parentId || null, startDate: form.startDate || null, dueDate: form.dueDate || null, plannedHours: form.plannedHours || null, version: item.version })); localStorage.removeItem(`description:${id}`);await load();refresh(); }catch(e){setError(getError(e));} };
  const remove = async () => { if(!item||!confirm(`Безвозвратно удалить «${item.title}»?`))return;try{await request(`/work-items/${id}`,{method:'DELETE',headers:{'X-Confirm-Hard-Delete':id}});close();refresh();}catch(e){setError(getError(e));} };
  const sendComment = async () => { if(!comment.trim())return;try{await request(`/work-items/${id}/comments`,json('POST',{body:comment}));setComment('');await load();refresh();}catch(e){setError(getError(e));} };
  const sendTime = async () => { try{await request(`/work-items/${id}/time-logs`,json('POST',{hours:logHours,loggedDate:logDate}));setLogHours('');await load();refresh();}catch(e){setError(getError(e));} };
  const upload = async (file: File) => { try{const data=new FormData();data.append('file',file);await request(`/work-items/${id}/attachments`,{method:'POST',body:data});await load();refresh();}catch(e){setError(getError(e));} };
  const download = async (a: Json) => { try{const user=await auth.getUser();const response=await fetch(`/api/v1/work-items/${id}/attachments/${a.id}`,{headers:{Authorization:`Bearer ${user?.access_token}`}});if(!response.ok)throw new Error('Не удалось скачать вложение');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=String(a.fileName);link.click();URL.revokeObjectURL(url);}catch(e){setError(getError(e));} };
  const showPreview = async (a: Json) => { try{const user=await auth.getUser();const response=await fetch(`/api/v1/work-items/${id}/attachments/${a.id}`,{headers:{Authorization:`Bearer ${user?.access_token}`}});if(!response.ok)throw new Error('Не удалось открыть вложение');const blob=await response.blob();setPreview({name:String(a.fileName),type:String(a.contentType),url:URL.createObjectURL(blob)});}catch(e){setError(getError(e));} };
  const removeAttachment = async (a: Json) => { if(!confirm('Удалить вложение?'))return;try{await request(`/work-items/${id}/attachments/${a.id}`,{method:'DELETE'});await load();refresh();}catch(e){setError(getError(e));} };
  const removeComment = async (c: Json) => { if(!confirm('Удалить комментарий?'))return;try{await request(`/work-items/${id}/comments/${c.id}`,{method:'DELETE'});await load();refresh();}catch(e){setError(getError(e));} };
  const editComment = async (c: Json) => { const value=prompt('Изменить комментарий',String(c.body));if(value===null)return;try{await request(`/work-items/${id}/comments/${c.id}`,json('PATCH',{body:value}));await load();refresh();}catch(e){setError(getError(e));} };
  const allowedChild = item?.type === 'PROJECT' ? 'EPIC' : item?.type === 'EPIC' ? 'TASK' : ['TASK','BUG'].includes(item?.type || '') ? 'SUBTASK' : null;
  return <div className="overlay" onMouseDown={close}><div className="item-dialog" role="dialog" aria-modal="true" aria-label="Карточка рабочего элемента" onMouseDown={e => e.stopPropagation()}><div className="dialog-title"><div><span className="eyebrow">{item ? `${typeName(item.type)} · ${id.slice(0,8)}` : 'ЗАГРУЗКА'}</span><h2>{item?.title || 'Рабочий элемент'}</h2></div><button onClick={close} aria-label="Закрыть">×</button></div><ErrorBanner message={error} clear={() => setError('')}/>
    {item && <div className="dialog-scroll"><div className="summary-strip"><div><small>План</small><strong>{hours(item.plannedHours)}</strong></div><div><small>Факт</small><strong>{hours(item.actualHours)}</strong></div><div><small>Остаток</small><strong className={item.remainingHours<0?'negative':''}>{hours(item.remainingHours)}</strong></div><div><small>Версия</small><strong>#{item.version}</strong></div></div>
      <div className="form-grid item-fields"><label>Название<input value={String(form.title ?? '')} onChange={e => set('title',e.target.value)} disabled={!can(context,'item.update')}/></label><label>Статус<select value={String(form.statusId ?? '')} onChange={e => set('statusId',e.target.value)} disabled={!can(context,'item.update')||!can(context,'item.status')}>{context.statuses.filter(s => s.active || s.id===item.statusId).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="span-2">Описание (Markdown)<textarea rows={5} value={String(form.description ?? '')} onChange={e => set('description',e.target.value)} disabled={!can(context,'item.update')}/><small>Черновик сохраняется в этом браузере до нажатия «Сохранить»</small></label><label>Приоритет<select value={String(form.priorityId ?? '')} onChange={e => set('priorityId',e.target.value)} disabled={!can(context,'item.update')}>{context.priorities.filter(p => p.active || p.id===item.priorityId).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Исполнитель<select value={String(form.assigneeId ?? '')} onChange={e => set('assigneeId',e.target.value)} disabled={!can(context,'item.update')}><option value="">Не назначен</option>{context.users.filter(u => u.active || u.id===item.assigneeId).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Дата начала<input type="date" value={String(form.startDate ?? '')} onChange={e => set('startDate',e.target.value)} disabled={!can(context,'item.update')}/></label><label>Срок<input type="date" value={String(form.dueDate ?? '')} onChange={e => set('dueDate',e.target.value)} disabled={!can(context,'item.update')}/></label><label>Плановая оценка, ч<input type="number" step="0.01" min="0" value={String(form.plannedHours ?? '')} onChange={e => set('plannedHours',e.target.value)} disabled={!can(context,'item.update')||item.children.length>0||['PROJECT','EPIC'].includes(item.type)}/></label><label>Родительский ID<input value={String(form.parentId ?? '')} onChange={e => set('parentId',e.target.value)} disabled={!can(context,'item.update')}/></label><div className="span-2 field-note">Итерация: {item.iterationId || 'не назначена'}{item.unestimatedLeaves>0 && <span className="warning"> · Есть элементы без оценки: {item.unestimatedLeaves}</span>}</div></div>
      <div className="hierarchy"><div className="mini-head"><h3>Иерархия</h3>{allowedChild && can(context,'item.create') && <button className="text-button" onClick={() => setChildForm(true)}>＋ Дочерний элемент</button>}</div>{item.parentId && <button className="link-row" onClick={() => open(item.parentId!)}>↑ Родительский элемент · {item.parentId.slice(0,8)}</button>}{item.children.length ? item.children.map(child => <button className="link-row" key={child.id} onClick={() => open(child.id)}>↳ {typeName(child.type)} · {child.title}</button>) : <p className="muted">Дочерних элементов нет</p>}</div>
      <div className="tabs" role="tablist">{([['discussion','Комментарии'],['time','Трудозатраты'],['files','Вложения'],['history','История']] as const).map(([key,label]) => <button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={() => setTab(key)}>{label}</button>)}</div>
      {tab==='discussion' && <div className="tab-body"><div className="stack">{comments.length ? comments.map(c => <div className="activity" key={String(c.id)}><div className="activity-meta"><strong>{selectName(context.users,String(c.authorId))}</strong><small>{dateTime(c.createdAt)}</small></div><p>{String(c.body)}</p>{(c.authorId===context.userId || can(context,'comment.manage')) && <div className="inline-actions"><button onClick={() => void editComment(c)}>Изменить</button><button onClick={() => void removeComment(c)}>Удалить</button></div>}</div>) : <Empty text="Комментариев пока нет"/>}</div>{can(context,'comment.create') && <div className="composer"><textarea placeholder="Написать комментарий" value={comment} onChange={e => setComment(e.target.value)}/><button className="button primary" onClick={() => void sendComment()}>Отправить</button></div>}</div>}
      {tab==='time' && <div className="tab-body"><div className="stack">{logs.length ? logs.map(log => <div className="activity" key={String(log.id)}><strong>{hours(log.hours)}</strong> · {date(log.loggedDate)} · {selectName(context.users,String(log.userId))}{Boolean(log.comment) && <p>{String(log.comment)}</p>}</div>) : <Empty text="Записей времени пока нет"/>}</div>{can(context,'time.create') && item.children.length===0 && !['PROJECT','EPIC'].includes(item.type) && <div className="composer row"><input type="date" value={logDate} onChange={e => setLogDate(e.target.value)}/><input aria-label="Часы" type="number" min="0.01" step="0.01" placeholder="Часы" value={logHours} onChange={e => setLogHours(e.target.value)}/><button className="button primary" onClick={() => void sendTime()}>Добавить время</button></div>}</div>}
      {tab==='files' && <div className="tab-body"><div className="stack">{attachments.length ? attachments.map(a => <div className="file-row" key={String(a.id)}><div><strong>{String(a.fileName)}</strong><small>{Math.round(Number(a.sizeBytes)/1024)} КБ · {dateTime(a.uploadedAt)}</small></div><div className="inline-actions">{(/^(image\/|text\/|application\/pdf$)/).test(String(a.contentType)) && <button onClick={() => void showPreview(a)}>Просмотр</button>}<button onClick={() => void download(a)}>Скачать</button>{can(context,'attachment.delete') && <button onClick={() => void removeAttachment(a)}>Удалить</button>}</div></div>) : <Empty text="Вложений пока нет"/>}</div>{can(context,'attachment.create') && <label className="button secondary file-button">＋ Прикрепить файл<input type="file" onChange={e => { const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''; }}/></label>}{preview && <div className="attachment-preview"><div className="mini-head"><strong>{preview.name}</strong><button onClick={() => setPreview(null)}>Закрыть</button></div>{preview.type.startsWith('image/') ? <img src={preview.url} alt={preview.name}/> : <iframe title={preview.name} src={preview.url}/>}</div>}</div>}
      {tab==='history' && <div className="tab-body"><div className="stack">{history.length ? history.map(entry => <details className="activity" key={String(entry.id)}><summary><strong>{String(entry.actorId || entry.externalSource || 'Система')}</strong><small>{dateTime(entry.occurredAt)}</small></summary><div className="diff-grid">{Object.entries(typeof entry.newValues==='string' ? JSON.parse(entry.newValues) : entry.newValues as Json).map(([key,value]) => <div className="diff-row" key={key}><strong>{key}</strong><del>{String((typeof entry.oldValues==='string'?JSON.parse(entry.oldValues):entry.oldValues as Json)?.[key] ?? '—')}</del><ins>{String(value ?? '—')}</ins></div>)}</div></details>) : <Empty text="Истории изменений пока нет"/>}</div></div>}
      <div className="dialog-actions sticky">{can(context,'item.delete') && <button className="button danger" onClick={() => void remove()}>Безвозвратно удалить</button>}{can(context,'item.update') && <button className="button primary" onClick={() => void save()}>Сохранить изменения</button>}<button className="button secondary" onClick={close}>Закрыть</button></div>
    </div>}
    {childForm && allowedChild && <CreateItem context={context} parentId={id} suggestedType={allowedChild} close={() => setChildForm(false)} created={childId => { setChildForm(false);refresh();open(childId); }}/>}</div></div>;
}

function Iterations({ context, revision, open, refresh }: { context: Context; revision: number; open: (id: string) => void; refresh: () => void }) {
  const [list, setList] = useState<Iteration[]>([]);const [selected, setSelected] = useState<string>('');const [iteration, setIteration] = useState<Iteration | null>(null);
  const [error, setError] = useState('');const [creating, setCreating] = useState(false);const [name, setName] = useState('');const [start, setStart] = useState('');const [end, setEnd] = useState('');
  const [itemId, setItemId] = useState('');const [capacityUser, setCapacityUser] = useState('');const [capacityHours, setCapacityHours] = useState('');
  const reload = useCallback(async () => { try { const rows = await request<Iteration[]>('/iterations');setList(rows);const id = selected || rows[0]?.id; if(id){setSelected(id);setIteration(await request<Iteration>(`/iterations/${id}`));}else setIteration(null); }catch(e){setError(getError(e));} },[selected]);
  useEffect(() => { void reload(); }, [reload, revision]);
  const action = async (path: string, init: RequestInit) => { try { await request(path,init);await reload();refresh(); }catch(e){setError(getError(e));} };
  const create = async (event: React.FormEvent) => {event.preventDefault();try{const row=await request<Iteration>('/iterations',json('POST',{name,startDate:start,endDate:end,description:''}));setCreating(false);setSelected(row.id);await reload();refresh();}catch(e){setError(getError(e));}};
  const canEdit = can(context,'iteration.write') && iteration?.state!=='COMPLETED';
  const baseline = iteration?.baseline || {};const result = iteration?.result || {};
  return <section className="screen-content"><div className="section-heading"><div><h2>Планирование итераций</h2><p>Ёмкость команды, состав и план-факт</p></div>{can(context,'iteration.write') && <button className="button primary" onClick={() => setCreating(true)}>＋ Новая итерация</button>}</div><ErrorBanner message={error} clear={() => setError('')}/><div className="iteration-layout"><div className="panel iteration-list"><h3>Итерации</h3>{list.length?list.map(row => <button key={row.id} className={`iteration-link ${selected===row.id?'active':''}`} onClick={() => setSelected(row.id)}><strong>{row.name}</strong><small>{date(row.startDate)} — {date(row.endDate)}</small><Badge tone={row.state==='COMPLETED'?'green':''}>{row.state}</Badge></button>):<Empty text="Итераций пока нет"/>}</div>
    <div className="iteration-detail">{iteration?<><div className="panel iteration-hero"><div className="section-heading"><div><span className="eyebrow">{iteration.state}</span><h2>{iteration.name}</h2><p>{date(iteration.startDate)} — {date(iteration.endDate)}</p></div>{can(context,'iteration.write') && <div className="actions">{iteration.state==='PLANNED' && <button className="button primary" onClick={() => void action(`/iterations/${iteration.id}/activate`,{method:'POST'})}>Запустить</button>}{iteration.state==='ACTIVE' && <button className="button primary" onClick={() => void action(`/iterations/${iteration.id}/complete`,{method:'POST'})}>Завершить</button>}</div>}</div><div className="metric-grid"><div><small>План</small><strong>{hours(iteration.plannedHours)}</strong></div><div><small>Факт</small><strong>{hours(iteration.actualHours)}</strong></div><div><small>Остаток</small><strong className={iteration.remainingHours<0?'negative':''}>{hours(iteration.remainingHours)}</strong></div><div><small>Готово</small><strong>{Math.round(iteration.completionFraction*100)}%</strong></div></div></div>
      {iteration.warnings.length>0 && <div className="warning-panel"><strong>Обратите внимание перед запуском</strong>{iteration.warnings.map((warning,index) => <p key={index}>{warning}</p>)}</div>}
      <div className="panel"><div className="mini-head"><h3>Загрузка участников</h3><span>Резерв команды: <strong className={iteration.teamReserveHours<0?'negative':''}>{hours(iteration.teamReserveHours)}</strong></span></div>{iteration.capacity.length?<div className="capacity-list">{iteration.capacity.map(entry => <div key={entry.userId} className="capacity-row"><strong>{selectName(context.users,entry.userId)}</strong><div className="capacity-track"><span style={{width:`${Math.min(100,entry.availableHours?entry.plannedHours/entry.availableHours*100:100)}%`}} className={entry.overloaded?'overload':''}/></div><small className={entry.overloaded?'negative':''}>{hours(entry.plannedHours)} / {hours(entry.availableHours)} · резерв {hours(entry.reserveHours)}</small></div>)}</div>:<Empty text="Ёмкость пока не задана"/>}{canEdit && <div className="composer row"><select aria-label="Участник" value={capacityUser} onChange={e => setCapacityUser(e.target.value)}><option value="">Участник</option>{context.users.filter(u => u.active).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><input aria-label="Доступные часы" type="number" min="0" step="0.01" placeholder="Доступные часы" value={capacityHours} onChange={e => setCapacityHours(e.target.value)}/><button className="button secondary" onClick={() => { if(capacityUser)void action(`/iterations/${iteration.id}/capacity`,json('PUT',{userId:capacityUser,availableHours:capacityHours})); }}>Сохранить ёмкость</button></div>}</div>
      <div className="panel"><div className="mini-head"><h3>Состав итерации</h3><span>{iteration.items.length} элементов</span></div>{iteration.items.length?<div className="stack">{iteration.items.map(item => <div className="file-row" key={item.id}><button className="text-button" onClick={() => open(item.id)}>{item.title} <small>· {typeName(item.type)}</small></button><div className="inline-actions"><span>{hours(item.plannedHours)}</span>{canEdit && <button onClick={() => void action(`/iterations/${iteration.id}/items/${item.id}`,{method:'DELETE'})}>Исключить</button>}</div></div>)}</div>:<Empty text="Добавьте элементы из бэклога"/>}{canEdit && <div className="composer row"><input aria-label="ID рабочего элемента" placeholder="ID рабочего элемента" value={itemId} onChange={e => setItemId(e.target.value)}/><button className="button secondary" onClick={() => { if(itemId)void action(`/iterations/${iteration.id}/items/${itemId}`,{method:'PUT'});setItemId(''); }}>Добавить</button></div>}</div>
      <div className="panel"><h3>Распределение по статусам</h3><div className="status-summary">{Object.entries(iteration.statusCounts).map(([status,count]) => <span key={status}><Badge>{status}</Badge> {count}</span>)}</div></div>
      {iteration.state==='COMPLETED' && <PlanFact baseline={baseline} result={result} context={context}/>}
    </>:<Empty text="Выберите итерацию"/>}</div></div>
    {creating && <div className="overlay" onMouseDown={() => setCreating(false)}><div className="small-dialog" onMouseDown={e => e.stopPropagation()}><div className="dialog-title"><h2>Новая итерация</h2><button onClick={() => setCreating(false)}>×</button></div><form className="form-grid" onSubmit={e => void create(e)}><label className="span-2">Название<input required value={name} onChange={e => setName(e.target.value)}/></label><label>Начало<input required type="date" value={start} onChange={e => setStart(e.target.value)}/></label><label>Окончание<input required type="date" value={end} onChange={e => setEnd(e.target.value)}/></label><div className="dialog-actions span-2"><button className="button primary">Создать</button></div></form></div></div>}</section>;
}

function PlanFact({ baseline, result, context }: { baseline: Json; result: Json; context: Context }) {
  const actual = (result.actual || {}) as Json;
  const plannedItems = (Array.isArray(baseline.items) ? baseline.items : []) as Item[];
  const actualItems = (Array.isArray(actual.items) ? actual.items : []) as Item[];
  const baselineCapacity = (Array.isArray(baseline.capacity) ? baseline.capacity : []) as Iteration['capacity'];
  const actualCapacity = (Array.isArray(actual.capacity) ? actual.capacity : []) as Iteration['capacity'];
  return <div className="panel"><h3>Сравнение плана и факта</h3><div className="metric-grid"><div><small>Базовый план</small><strong>{hours(baseline.plannedHours)}</strong></div><div><small>Факт на завершение</small><strong>{hours(actual.actualHours)}</strong></div><div><small>Отклонение</small><strong>{hours(result.deviationHours)}</strong></div></div><h4>По элементам</h4><div className="table-scroll"><table><thead><tr><th>Элемент</th><th>План при запуске</th><th>План при завершении</th><th>Факт</th><th>Отклонение</th></tr></thead><tbody>{plannedItems.map(item => {const current=actualItems.find(row => row.id===item.id);return <tr key={item.id}><td>{item.title}</td><td>{hours(item.plannedHours)}</td><td>{current?hours(current.plannedHours):'Исключён'}</td><td>{hours(current?.actualHours)}</td><td className={Number(current?.actualHours||0)>Number(item.plannedHours)?'negative':''}>{hours(Number(current?.actualHours||0)-Number(item.plannedHours))}</td></tr>;})}</tbody></table></div><h4>По исполнителям</h4><div className="table-scroll"><table><thead><tr><th>Исполнитель</th><th>План при запуске</th><th>План при завершении</th><th>Факт</th><th>Отклонение</th><th>Ёмкость</th></tr></thead><tbody>{baselineCapacity.map(entry => {const current=actualCapacity.find(row => row.userId===entry.userId);const comparison=compareAssignee(entry,current);return <tr key={entry.userId}><td>{selectName(context.users,entry.userId)}</td><td>{hours(comparison.planned)}</td><td>{hours(comparison.currentPlan)}</td><td>{hours(comparison.actual)}</td><td className={comparison.deviation>0?'negative':''}>{hours(comparison.deviation)}</td><td>{hours(comparison.available)}</td></tr>;})}</tbody></table></div></div>;
}

function Notifications({ open, revision, refresh }: { open: (id: string) => void; revision: number; refresh: () => void }) {
  const [rows,setRows]=useState<Array<Json>>([]);const [error,setError]=useState('');
  useEffect(() => { request<Array<Json>>('/notifications').then(setRows).catch(e => setError(getError(e))); },[revision]);
  const mark = async (row: Json) => {try{await request(`/notifications/${row.id}`,{method:'PATCH'});refresh();}catch(e){setError(getError(e));}};
  return <section className="screen-content"><div className="section-heading"><div><h2>Последние изменения</h2><p>Уведомления о назначениях и событиях ваших задач</p></div></div><ErrorBanner message={error} clear={() => setError('')}/><div className="panel notification-list">{rows.length?rows.map(row => <div className={`notification ${row.readAt?'':'unread'}`} key={String(row.id)}><span className="notification-dot"/><div><strong>{String(row.message)}</strong><p>{String(row.workItemTitle)} · {dateTime(row.createdAt)} · {String(row.actor)}</p><div className="inline-actions">{Boolean(row.workItemId) && <button onClick={() => open(String(row.workItemId))}>Открыть карточку</button>}{!row.readAt && <button onClick={() => void mark(row)}>Отметить прочитанным</button>}</div></div></div>):<Empty text="Уведомлений пока нет"/>}</div></section>;
}

function Admin({ context, refreshAll }: { context: Context; refreshAll: () => void }) {
  const [section,setSection]=useState<'statuses'|'priorities'|'types'|'access'|'directory'>('statuses');
  useEffect(() => { const rights = { statuses:'status.admin', priorities:'priority.admin', types:'type.admin', access:'access.admin', directory:'directory.admin' } as const;
    if(!can(context,rights[section])) { const first=(Object.keys(rights) as Array<keyof typeof rights>).find(key=>can(context,rights[key]));if(first)setSection(first); }
  },[context,section]);
  const [accessRows,setAccessRows]=useState<Array<Json>>([]);const [permissions,setPermissions]=useState<Array<Json>>([]);const [directory,setDirectory]=useState<Json>({});const [error,setError]=useState('');
  const reload = useCallback(async () => {try{const [a,p,d]=await Promise.all([can(context,'access.admin')?request<Array<Json>>('/admin/access'):Promise.resolve([]),can(context,'access.admin')?request<Array<Json>>('/admin/permissions'):Promise.resolve([]),can(context,'directory.admin')?request<Json>('/admin/directory'):Promise.resolve({})]);setAccessRows(a);setPermissions(p);setDirectory(d);}catch(e){setError(getError(e));}},[context]);
  useEffect(() => {void reload();},[reload]);
  const action = async (path:string,init:RequestInit) => {try{await request(path,init);await reload();refreshAll();}catch(e){setError(getError(e));}};
  const createStatus = () => {const name=prompt('Название нового статуса');if(name)void action('/admin/statuses',json('POST',{name,boardOrder:context.statuses.length+1,category:'OPEN',boardVisible:true}));};
  const createPriority = () => {const name=prompt('Название нового приоритета');if(name)void action('/admin/priorities',json('POST',{name,sortOrder:context.priorities.length+1}));};
  return <section className="screen-content"><div className="section-heading"><div><h2>Настройки процесса</h2><p>Статусы, приоритеты, доступ и справочник организации</p></div></div><ErrorBanner message={error} clear={() => setError('')}/><div className="tabs admin-tabs">{([['statuses','Статусы','status.admin'],['priorities','Приоритеты','priority.admin'],['types','Типы','type.admin'],['access','Права','access.admin'],['directory','Справочник','directory.admin']] as const).filter(([, ,permission]) => can(context,permission)).map(([key,label]) => <button key={key} className={section===key?'active':''} onClick={() => setSection(key)}>{label}</button>)}</div>
    {section==='statuses' && <div className="panel"><div className="mini-head"><h3>Колонки доски</h3><button className="button secondary" onClick={createStatus}>＋ Статус</button></div><div className="settings-list">{context.statuses.map(row => <div className="setting-row" key={row.id}><input aria-label="Название" defaultValue={row.name} onBlur={e => {if(e.target.value!==row.name)void action(`/admin/statuses/${row.id}`,json('PATCH',{name:e.target.value}));}}/><input aria-label="Порядок" type="number" className="small-input" defaultValue={row.boardOrder} onBlur={e => {if(Number(e.target.value)!==row.boardOrder)void action(`/admin/statuses/${row.id}`,json('PATCH',{boardOrder:Number(e.target.value)}));}}/><select aria-label="Категория" value={row.category} onChange={e => void action(`/admin/statuses/${row.id}`,json('PATCH',{category:e.target.value}))}><option value="OPEN">В работе</option><option value="COMPLETED">Завершение</option><option value="ARCHIVED">Архив</option></select><label><input type="checkbox" checked={row.boardVisible} onChange={e => void action(`/admin/statuses/${row.id}`,json('PATCH',{boardVisible:e.target.checked}))}/> На доске</label><label><input type="checkbox" checked={row.active} onChange={e => void action(`/admin/statuses/${row.id}`,json('PATCH',{active:e.target.checked}))}/> Активен</label></div>)}</div></div>}
    {section==='priorities' && <div className="panel"><div className="mini-head"><h3>Приоритеты</h3><button className="button secondary" onClick={createPriority}>＋ Приоритет</button></div><div className="settings-list">{context.priorities.map(row => <div className="setting-row" key={row.id}><input aria-label="Название" defaultValue={row.name} onBlur={e => {if(e.target.value!==row.name)void action(`/admin/priorities/${row.id}`,json('PATCH',{name:e.target.value}));}}/><input aria-label="Порядок" className="small-input" type="number" defaultValue={row.sortOrder} onBlur={e => {if(Number(e.target.value)!==row.sortOrder)void action(`/admin/priorities/${row.id}`,json('PATCH',{sortOrder:Number(e.target.value)}));}}/><Badge>{row.code || 'Пользовательский'}</Badge><label><input type="checkbox" checked={row.active} onChange={e => void action(`/admin/priorities/${row.id}`,json('PATCH',{active:e.target.checked}))}/> Активен</label></div>)}</div></div>}
    {section==='types' && <div className="panel"><h3>Доступность типов</h3><div className="settings-list">{context.types.map(row => <div className="setting-row" key={row.type}><strong>{typeName(row.type)}</strong><label><input type="checkbox" checked={row.enabled} onChange={e => void action(`/admin/types/${row.type}`,json('PATCH',{enabled:e.target.checked}))}/> Доступен для создания</label></div>)}</div></div>}
    {section==='access' && <div className="panel"><h3>Локальный допуск</h3><div className="settings-list">{context.users.map(user => {const row=accessRows.find(entry => entry.userId===user.id);return <div className="setting-row" key={user.id}><strong>{user.name}</strong><select aria-label={`Роль ${user.name}`} value={String(row?.role||'MEMBER')} onChange={e => void action(`/admin/access/${user.id}`,json('PUT',{role:e.target.value,allowed:row?.allowed??true}))}><option value="MEMBER">Участник</option><option value="LEAD">Руководитель</option><option value="ADMIN">Администратор</option></select><label><input type="checkbox" checked={Boolean(row?.allowed)} onChange={e => void action(`/admin/access/${user.id}`,json('PUT',{role:row?.role||'MEMBER',allowed:e.target.checked}))}/> Допущен</label></div>;})}</div><h3>Разрешения ролей</h3><div className="permission-grid">{permissions.map(row => <label key={`${row.role}:${row.permission}`}><input type="checkbox" checked={Boolean(row.allowed)} onChange={e => void action(`/admin/permissions/${row.role}/${row.permission}`,json('PUT',{allowed:e.target.checked}))}/><span>{String(row.role)} · {String(row.permission)}</span></label>)}</div></div>}
    {section==='directory' && <div className="panel"><div className="mini-head"><div><h3>Синхронизация справочника</h3><p>Последний успех: {dateTime(directory.lastSuccessAt)}</p><p>Версия: {String(directory.version || '—')}</p></div><button className="button primary" onClick={() => void action('/admin/directory/sync',{method:'POST'})}>Синхронизировать</button></div><h4>Журнал</h4><div className="stack">{Array.isArray(directory.logs) && directory.logs.length ? (directory.logs as Array<Json>).map(row => <div className="activity" key={String(row.id)}><Badge tone={row.success?'green':'red'}>{row.success?'Успех':'Ошибка'}</Badge> {dateTime(row.occurredAt)} · {String(row.message)} · {String(row.durationMs)} мс</div>):<Empty text="Запусков синхронизации пока нет"/>}</div></div>}
  </section>;
}
