version: '3'

tasks:
  generate:
    desc: Generate all artifacts
    cmds:
      - go tool oapi-codegen -config api/openapi/v1/codegen.server.yaml api/openapi/v1/openapi.yaml
      - go tool oapi-codegen -config api/openapi/v1/codegen.models.yaml api/openapi/v1/openapi.yaml

  lint:
    desc: Run linter checks (pass extra flags after '--', e.g., 'task lint -- --fix')
    cmds:
      - golangci-lint run ./... {{.CLI_ARGS}}

  tests:
    desc: Run all tests
    deps: [lint]
    cmds:
      - echo "not implemented"

  migration:
    desc: Create new migration file
    cmds:
      - migrate create -ext sql -dir deployments/migrations -seq {{.CLI_ARGS}}

  build:
    desc: Build Docker image for the reference manager application
    cmds:
      - docker build -f deployments/docker/reference-manager.dockerfile -t erp/reference-manager:latest .

  up:
    desc: Start the local development environment using Docker Compose
    cmds:
      - docker compose -f deployments/docker-compose.yaml up -d --build
  
  down:
    desc: Stop the local environment and remove associated volumes
    cmds:
      - docker compose -f deployments/docker-compose.yaml down -v
