version: '3'

tasks:
  generate:
    desc: Generate all artifacts
    cmds:
      - |
        find api/openapi/v1 -type f -name 'openapi.yaml' | sort | while read -r spec; do
          dir="$(dirname "$spec")"

          for config in "$dir"/codegen.*.yaml; do
            [ -f "$config" ] || continue

            echo "Generating: $config"
            go tool oapi-codegen -config "$config" "$spec"
          done
        done

  lint:
    desc: Run all linters checks (pass extra flags after '--', e.g., 'task lint -- --fix')
    cmds:
      - golangci-lint run ./... {{.CLI_ARGS}}
      - docker run --rm -i ghcr.io/hadolint/hadolint:latest < deployments/docker/reference-manager.dockerfile

  tests:
    desc: Run all tests
    cmds:
      - echo "not implemented"

  migration:
    desc: Create new migration file
    cmds:
      - migrate create -ext sql -dir deployments/migrations -seq {{.CLI_ARGS}}

  build:
    desc: Build Docker image for the reference manager application
    cmds:
      - docker build -f deployments/docker/reference-manager.dockerfile -t erp/reference-manager:latest .

  up:
    desc: Start the local development environment using Docker Compose
    cmds:
      - docker compose -f deployments/docker-compose.yaml up -d --build
  
  down:
    desc: Stop the local environment and remove associated volumes
    cmds:
      - docker compose -f deployments/docker-compose.yaml down -v

  swagger:
    desc: Run Swagger UI
    silent: true
    cmds:
      - |
        URLS="$(
          find api/openapi/v1 -mindepth 2 -type f -name 'openapi.yaml' \
            | sort \
            | awk -F/ '{
                name=$(NF-1)
                printf "%s{\"name\":\"%s\",\"url\":\"/specs/%s/openapi.yaml\"}",
                  sep, name, name
                sep=","
              } END { print "" }'
        )"

        docker run --rm \
          -p 8083:8080 \
          -v "$(pwd)/api/openapi/v1:/usr/share/nginx/html/specs:ro" \
          -e URLS="[$URLS]" \
          docker.swagger.io/swaggerapi/swagger-ui