// Package currencyv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package currencyv1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Currency Base representation of a currency according to the ISO 4217 standard.
type Currency struct {
	// CodeAlpha Three-letter ISO 4217 alphabetic code.
	//
	// Example: USD
	CodeAlpha *string `json:"code_alpha,omitempty"`

	// CodeNum Three-letter ISO 4217 numeric code.
	//
	// Example: 840
	CodeNum *string `json:"code_num,omitempty"`

	// Id Unique identifier of the currency.
	//
	// Example: 1
	Id *int64 `json:"id,omitempty"`

	// MinorUnits Number of minor units (decimal places).
	//
	// Example: 2
	MinorUnits *int32 `json:"minor_units,omitempty"`

	// Name Full official name of the currency.
	//
	// Example: United States Dollar
	Name *string `json:"name,omitempty"`

	// Symbol Currency symbol.
	//
	// Example: $
	Symbol *string `json:"symbol,omitempty"`
}

// CurrencyRevision Represents a historical revision or change log entry for a currency.
type CurrencyRevision struct {
	// Change Arbitrary JSON object representing the exact changes made to the currency fields.
	// Contains only the modified fields and their new values.
	//
	//
	// Example: {"minor_units":2,"name":"United States Dollar (Updated)"}
	Change *map[string]interface{} `json:"change,omitempty"`

	// ChangedAt Timestamp of when the change was applied.
	//
	// Example: 2026-10-03T09:30:00Z
	ChangedAt *time.Time `json:"changed_at,omitempty"`

	// ChangedBy UUID of the user or system that performed the change.
	//
	// Example: 123e4567-e89b-12d3-a456-426614174000
	ChangedBy *openapi_types.UUID `json:"changed_by,omitempty"`

	// CurrencyId Identifier of the currency this revision belongs to.
	//
	// Example: 1
	CurrencyId *int64 `json:"currency_id,omitempty"`

	// Id Unique identifier of the revision record.
	//
	// Example: 101
	Id *int64 `json:"id,omitempty"`

	// Revision The revision number associated with this change.
	//
	// Example: 4
	Revision *int32 `json:"revision,omitempty"`
}

// ExpandedCurrency Extended representation of a currency including audit and revision tracking fields.
type ExpandedCurrency struct {
	// CodeAlpha Three-letter ISO 4217 alphabetic code.
	//
	// Example: USD
	CodeAlpha *string `json:"code_alpha,omitempty"`

	// CodeNum Three-letter ISO 4217 numeric code.
	//
	// Example: 840
	CodeNum *string `json:"code_num,omitempty"`

	// CreatedAt Timestamp of when the currency record was created.
	//
	// Example: 2023-10-25T14:48:00Z
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique identifier of the currency.
	//
	// Example: 1
	Id *int64 `json:"id,omitempty"`

	// LastChanger UUID of the user or system that last modified this record.
	//
	// Example: 123e4567-e89b-12d3-a456-426614174000
	LastChanger *openapi_types.UUID `json:"last_changer,omitempty"`

	// MinorUnits Number of minor units (decimal places).
	//
	// Example: 2
	MinorUnits *int32 `json:"minor_units,omitempty"`

	// Name Full official name of the currency.
	//
	// Example: United States Dollar
	Name *string `json:"name,omitempty"`

	// Revision Current revision number of the currency record.
	//
	// Example: 5
	Revision *int32 `json:"revision,omitempty"`

	// Symbol Currency symbol.
	//
	// Example: $
	Symbol *string `json:"symbol,omitempty"`

	// UpdatedAt Timestamp of the last update to the currency record.
	//
	// Example: 2026-10-03T10:00:00Z
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ListCurrenciesResponse Paginated list of expanded currencies.
type ListCurrenciesResponse struct {
	// Currencies List of currencies for the current page.
	Currencies []struct {
		// CodeAlpha Three-letter ISO 4217 alphabetic code.
		//
		// Example: USD
		CodeAlpha *string `json:"code_alpha,omitempty"`

		// CodeNum Three-letter ISO 4217 numeric code.
		//
		// Example: 840
		CodeNum *string `json:"code_num,omitempty"`

		// CreatedAt Timestamp of when the currency record was created.
		//
		// Example: 2023-10-25T14:48:00Z
		CreatedAt *time.Time `json:"created_at,omitempty"`

		// Id Unique identifier of the currency.
		//
		// Example: 1
		Id *int64 `json:"id,omitempty"`

		// LastChanger UUID of the user or system that last modified this record.
		//
		// Example: 123e4567-e89b-12d3-a456-426614174000
		LastChanger *openapi_types.UUID `json:"last_changer,omitempty"`

		// MinorUnits Number of minor units (decimal places).
		//
		// Example: 2
		MinorUnits *int32 `json:"minor_units,omitempty"`

		// Name Full official name of the currency.
		//
		// Example: United States Dollar
		Name *string `json:"name,omitempty"`

		// Revision Current revision number of the currency record.
		//
		// Example: 5
		Revision *int32 `json:"revision,omitempty"`

		// Symbol Currency symbol.
		//
		// Example: $
		Symbol *string `json:"symbol,omitempty"`

		// UpdatedAt Timestamp of the last update to the currency record.
		//
		// Example: 2026-10-03T10:00:00Z
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
	} `json:"currencies"`

	// NextPageToken Token to retrieve the next page of results. Empty if no more results.
	//
	// Example: eyJpZCI6MTAwfQ==
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ListRevisionsResponse Paginated list of currency revisions.
type ListRevisionsResponse struct {
	// NextPageToken Token to retrieve the next page of results.
	//
	// Example: eyJyZXZpc2lvbiI6MTB9
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Revisions List of revisions for the current page.
	Revisions []struct {
		// Change Arbitrary JSON object representing the exact changes made to the currency fields.
		// Contains only the modified fields and their new values.
		//
		//
		// Example: {"minor_units":2,"name":"United States Dollar (Updated)"}
		Change *map[string]interface{} `json:"change,omitempty"`

		// ChangedAt Timestamp of when the change was applied.
		//
		// Example: 2026-10-03T09:30:00Z
		ChangedAt *time.Time `json:"changed_at,omitempty"`

		// ChangedBy UUID of the user or system that performed the change.
		//
		// Example: 123e4567-e89b-12d3-a456-426614174000
		ChangedBy *openapi_types.UUID `json:"changed_by,omitempty"`

		// CurrencyId Identifier of the currency this revision belongs to.
		//
		// Example: 1
		CurrencyId *int64 `json:"currency_id,omitempty"`

		// Id Unique identifier of the revision record.
		//
		// Example: 101
		Id *int64 `json:"id,omitempty"`

		// Revision The revision number associated with this change.
		//
		// Example: 4
		Revision *int32 `json:"revision,omitempty"`
	} `json:"revisions"`
}

// ListCurrenciesParams defines parameters for ListCurrencies.
type ListCurrenciesParams struct {
	// PageSize Maximum number of currencies to return (1-1000).
	PageSize *int32 `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Token for pagination, obtained from a previous list request.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateCurrencyJSONBody defines parameters for CreateCurrency.
type CreateCurrencyJSONBody struct {
	// CodeAlpha Three-letter ISO 4217 alphabetic code.
	//
	// Example: USD
	CodeAlpha *string `json:"code_alpha,omitempty"`

	// CodeNum Three-letter ISO 4217 numeric code.
	//
	// Example: 840
	CodeNum *string `json:"code_num,omitempty"`

	// Id Unique identifier of the currency.
	//
	// Example: 1
	Id *int64 `json:"id,omitempty"`

	// MinorUnits Number of minor units (decimal places).
	//
	// Example: 2
	MinorUnits *int32 `json:"minor_units,omitempty"`

	// Name Full official name of the currency.
	//
	// Example: United States Dollar
	Name *string `json:"name,omitempty"`

	// Symbol Currency symbol.
	//
	// Example: $
	Symbol *string `json:"symbol,omitempty"`
}

// UpdateCurrencyJSONBody defines parameters for UpdateCurrency.
type UpdateCurrencyJSONBody struct {
	// CodeAlpha Three-letter ISO 4217 alphabetic code.
	//
	// Example: USD
	CodeAlpha *string `json:"code_alpha,omitempty"`

	// CodeNum Three-letter ISO 4217 numeric code.
	//
	// Example: 840
	CodeNum *string `json:"code_num,omitempty"`

	// Id Unique identifier of the currency.
	//
	// Example: 1
	Id *int64 `json:"id,omitempty"`

	// MinorUnits Number of minor units (decimal places).
	//
	// Example: 2
	MinorUnits *int32 `json:"minor_units,omitempty"`

	// Name Full official name of the currency.
	//
	// Example: United States Dollar
	Name *string `json:"name,omitempty"`

	// Symbol Currency symbol.
	//
	// Example: $
	Symbol *string `json:"symbol,omitempty"`
}

// UpdateCurrencyParams defines parameters for UpdateCurrency.
type UpdateCurrencyParams struct {
	// UpdateMask Comma-separated list of fields to update (e.g., "name,symbol").
	// If "*", all provided fields in the body will be updated.
	UpdateMask string `form:"update_mask" json:"update_mask"`
}

// ListCurrencyRevisionsParams defines parameters for ListCurrencyRevisions.
type ListCurrencyRevisionsParams struct {
	PageSize  *int32  `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateCurrencyJSONRequestBody defines body for CreateCurrency for application/json ContentType.
type CreateCurrencyJSONRequestBody CreateCurrencyJSONBody

// UpdateCurrencyJSONRequestBody defines body for UpdateCurrency for application/json ContentType.
type UpdateCurrencyJSONRequestBody UpdateCurrencyJSONBody
