// Package currencyv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package currencyv1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExportCurrenciesJSONBodyFields.
const (
	Code      ExportCurrenciesJSONBodyFields = "code"
	CreatedAt ExportCurrenciesJSONBodyFields = "created_at"
	Decimals  ExportCurrenciesJSONBodyFields = "decimals"
	Name      ExportCurrenciesJSONBodyFields = "name"
	Number    ExportCurrenciesJSONBodyFields = "number"
	Revision  ExportCurrenciesJSONBodyFields = "revision"
	UpdatedAt ExportCurrenciesJSONBodyFields = "updated_at"
)

// Valid indicates whether the value is a known member of the ExportCurrenciesJSONBodyFields enum.
func (e ExportCurrenciesJSONBodyFields) Valid() bool {
	switch e {
	case Code:
		return true
	case CreatedAt:
		return true
	case Decimals:
		return true
	case Name:
		return true
	case Number:
		return true
	case Revision:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ExportCurrenciesJSONBodyFormat.
const (
	Csv  ExportCurrenciesJSONBodyFormat = "csv"
	Xlsx ExportCurrenciesJSONBodyFormat = "xlsx"
)

// Valid indicates whether the value is a known member of the ExportCurrenciesJSONBodyFormat enum.
func (e ExportCurrenciesJSONBodyFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Xlsx:
		return true
	default:
		return false
	}
}

// Currency Currency information in accordance with the ISO 4217 standard. Includes alphabetic and numeric codes, the name, and rounding precision.
type Currency struct {
	// Code Three-letter international currency code (alphabetic code). Always consists of three uppercase Latin letters.
	Code string `json:"code"`

	// Decimals The number of decimal places (minor units) for fractional parts (cents, kopecks). Usually 2, but there are exceptions (e.g., 0 for JPY or 3 for BHD).
	Decimals int `json:"decimals"`

	// Name Official name of the currency in Russian or English.
	Name string `json:"name"`

	// Number Three-digit numeric currency code.  Passed as a string to preserve leading zeros (e.g., '840' for USD).
	Number string `json:"number"`
}

// CurrencyRevision Currency revision record reflecting changes made to currency data. This model is read-only.
type CurrencyRevision struct {
	// Change Changes applied in this revision relative to the previous one, formatted as a JSON Patch (RFC 6902).
	Change *[]map[string]interface{} `json:"change,omitempty"`

	// ChangedAt The date and time when the change was applied.
	ChangedAt *time.Time `json:"changed_at,omitempty"`

	// ChangedBy UUID of the user or system component that performed the change.
	ChangedBy *openapi_types.UUID `json:"changed_by,omitempty"`

	// CurrencyId Identifier of the currency this revision belongs to (references ISO 4217 standard currency data).
	CurrencyId *int64 `json:"currency_id,omitempty"`

	// Id Unique identifier of the revision record.
	Id *int64 `json:"id,omitempty"`

	// RevisionNumber The sequential number of the revision, starting from 1.
	RevisionNumber *int `json:"revision_number,omitempty"`
}

// CurrencyUpdate Schema for partial updates to currency information. All fields are optional since this is used for PATCH operations. Only provided fields will be updated.
type CurrencyUpdate struct {
	// Code Three-letter international currency code (alphabetic code). Always consists of three uppercase Latin letters.
	Code *string `json:"code,omitempty"`

	// Decimals The number of decimal places (minor units) for fractional parts (cents, kopecks). Usually 2, but there are exceptions (e.g., 0 for JPY or 3 for BHD).
	Decimals *int `json:"decimals,omitempty"`

	// Name Official name of the currency in Russian or English.
	Name *string `json:"name,omitempty"`

	// Number Three-digit numeric currency code.  Passed as a string to preserve leading zeros (e.g., '840' for USD).
	Number *string `json:"number,omitempty"`
}

// Error Standardized error response format for all API errors.
type Error struct {
	// Details Optional array of detailed error information. Can include field-specific validation errors or additional context.
	Details *[]ErrorDetail `json:"details,omitempty"`

	// ErrorCode Machine-readable error code that identifies the type of error. Uses UPPER_SNAKE_CASE format for consistency.
	ErrorCode string `json:"error_code"`

	// Message Human-readable error message describing what went wrong.
	Message string `json:"message"`
}

// ErrorDetail Detailed information about a specific error or validation issue.
type ErrorDetail struct {
	// Constraint The validation constraint that was violated (if applicable).
	Constraint *string `json:"constraint,omitempty"`

	// Field The field name that caused the error (if applicable).
	Field *string `json:"field,omitempty"`

	// Message Specific error message for this field or detail.
	Message *string `json:"message,omitempty"`

	// Value The invalid value that was provided (if applicable).
	Value *string `json:"value,omitempty"`
}

// ExpandedCurrency Currency information in accordance with the ISO 4217 standard. Includes alphabetic and numeric codes, the name, and rounding precision.
type ExpandedCurrency struct {
	// Code Three-letter international currency code (alphabetic code). Always consists of three uppercase Latin letters.
	Code string `json:"code"`

	// CreatedAt The date and time when the currency record was initially created.
	CreatedAt time.Time `json:"created_at"`

	// Decimals The number of decimal places (minor units) for fractional parts (cents, kopecks). Usually 2, but there are exceptions (e.g., 0 for JPY or 3 for BHD).
	Decimals int `json:"decimals"`

	// LastChanger UUID of the user or system component that performed the latest change.
	LastChanger openapi_types.UUID `json:"last_changer"`

	// Name Official name of the currency in Russian or English.
	Name string `json:"name"`

	// Number Three-digit numeric currency code.  Passed as a string to preserve leading zeros (e.g., '840' for USD).
	Number string `json:"number"`

	// Revision The sequential number of the latest revision applied to this currency.
	Revision int `json:"revision"`

	// UpdatedAt The date and time when the currency record was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ImportError Details about an error encountered during currency import.
type ImportError struct {
	// Field Field that caused the validation error
	Field *string `json:"field,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// Row Row number in the Excel file where the error occurred
	Row *int `json:"row,omitempty"`

	// Value The invalid value that was provided
	Value *string `json:"value,omitempty"`
}

// CurrencyID defines model for CurrencyID.
type CurrencyID = int64

// ListPageSize defines model for ListPageSize.
type ListPageSize = int

// ListPageToken defines model for ListPageToken.
type ListPageToken = string

// BadRequest Standardized error response format for all API errors.
type BadRequest = Error

// Conflict Standardized error response format for all API errors.
type Conflict = Error

// CurrencyCreated Currency information in accordance with the ISO 4217 standard. Includes alphabetic and numeric codes, the name, and rounding precision.
type CurrencyCreated = ExpandedCurrency

// NotFound Standardized error response format for all API errors.
type NotFound = Error

// UnprocessableEntity Standardized error response format for all API errors.
type UnprocessableEntity = Error

// GetV1CurrenciesParams defines parameters for GetV1Currencies.
type GetV1CurrenciesParams struct {
	// PageSize Number of elements per page
	PageSize *ListPageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// PageToken Pagination token for retrieving the next page of results. Use the token from the previous response to get the next page.
	PageToken *ListPageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// ExportCurrenciesJSONBody defines parameters for ExportCurrencies.
type ExportCurrenciesJSONBody struct {
	// Fields Fields to include in the export. If not specified, all fields will be included.
	Fields  *[]ExportCurrenciesJSONBodyFields `json:"fields,omitempty"`
	Filters *struct {
		// Codes Filter by specific currency codes
		Codes *[]string `json:"codes,omitempty"`

		// CreatedAfter Filter currencies created after this date
		CreatedAfter *time.Time `json:"created_after,omitempty"`

		// UpdatedAfter Filter currencies updated after this date
		UpdatedAfter *time.Time `json:"updated_after,omitempty"`
	} `json:"filters,omitempty"`

	// Format Output file format
	Format *ExportCurrenciesJSONBodyFormat `json:"format,omitempty"`
}

// ExportCurrenciesJSONBodyFields defines parameters for ExportCurrencies.
type ExportCurrenciesJSONBodyFields string

// ExportCurrenciesJSONBodyFormat defines parameters for ExportCurrencies.
type ExportCurrenciesJSONBodyFormat string

// ImportCurrenciesMultipartBody defines parameters for ImportCurrencies.
type ImportCurrenciesMultipartBody struct {
	// File Excel file (.xlsx or .xls) containing currency data
	File openapi_types.File `json:"file"`

	// ValidateOnly If true, only validate the file without importing. Returns validation results without creating records.
	ValidateOnly *bool `json:"validateOnly,omitempty"`
}

// ListCurrencyRevisionsParams defines parameters for ListCurrencyRevisions.
type ListCurrencyRevisionsParams struct {
	// PageSize Number of revisions per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// PageToken Pagination token for retrieving the next page
	PageToken *string `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// CreateCurrencyJSONRequestBody defines body for CreateCurrency for application/json ContentType.
type CreateCurrencyJSONRequestBody = Currency

// ExportCurrenciesJSONRequestBody defines body for ExportCurrencies for application/json ContentType.
type ExportCurrenciesJSONRequestBody ExportCurrenciesJSONBody

// ImportCurrenciesMultipartRequestBody defines body for ImportCurrencies for multipart/form-data ContentType.
type ImportCurrenciesMultipartRequestBody ImportCurrenciesMultipartBody

// UpdateCurrencyJSONRequestBody defines body for UpdateCurrency for application/json ContentType.
type UpdateCurrencyJSONRequestBody = CurrencyUpdate
