// Package currency provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package currency

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateCurrencyJSONBody defines parameters for CreateCurrency.
type CreateCurrencyJSONBody struct {
	// Code ISO 4217 alphabetic currency code.
	//
	// Example: EUR
	Code string `json:"code"`

	// CreateTime Time when the currency was created.
	CreateTime *time.Time `json:"createTime,omitempty"`

	// DisplayName Human-readable currency name.
	//
	// Example: Euro
	DisplayName string `json:"displayName"`

	// MinorUnits Number of decimal digits used for the minor currency unit.
	//
	// Example: 2
	MinorUnits *int32 `json:"minorUnits,omitempty"`

	// Name Resource name of the currency.
	//
	// Format: currencies/{currency}
	//
	//
	// Example: currencies/eur
	Name *string `json:"name,omitempty"`

	// NumericCode ISO 4217 numeric currency code.
	//
	// Example: 978
	NumericCode string `json:"numericCode"`

	// Uid System-assigned unique identifier of the currency.
	//
	// Example: 550e8400-e29b-41d4-a716-446655440000
	Uid *openapi_types.UUID `json:"uid,omitempty"`

	// UpdateTime Time when the currency was last updated.
	UpdateTime *time.Time `json:"updateTime,omitempty"`
}

// CreateCurrencyParams defines parameters for CreateCurrency.
type CreateCurrencyParams struct {
	// CurrencyId User-specified identifier of the currency resource.
	//
	// The identifier must be the lowercase ISO 4217 alphabetic code.
	CurrencyId string `form:"currencyId" json:"currencyId"`
}

// CreateCurrencyJSONRequestBody defines body for CreateCurrency for application/json ContentType.
type CreateCurrencyJSONRequestBody CreateCurrencyJSONBody
