// Package currencyv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package currencyv1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCurrencies List currencies with pagination
	// (GET /v1/currencies/)
	ListCurrencies(w http.ResponseWriter, r *http.Request, params ListCurrenciesParams)
	// CreateCurrency Create new currency record
	// (POST /v1/currencies/)
	CreateCurrency(w http.ResponseWriter, r *http.Request)
	// ExportCurrencies Export currencies in Excel format
	// (POST /v1/currencies/export)
	ExportCurrencies(w http.ResponseWriter, r *http.Request)
	// DeleteCurrency Delete currency record
	// (DELETE /v1/currencies/{currencyID})
	DeleteCurrency(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params DeleteCurrencyParams)
	// GetCurrency Get currency by ID
	// (GET /v1/currencies/{currencyID})
	GetCurrency(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params GetCurrencyParams)
	// UpdateCurrency Update currency information
	// (PATCH /v1/currencies/{currencyID})
	UpdateCurrency(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params UpdateCurrencyParams)
	// ListCurrencyRevisions List all revisions for a currency
	// (GET /v1/currencies/{currencyID}/revisions)
	ListCurrencyRevisions(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params ListCurrencyRevisionsParams)
	// GetCurrencyRevision Get specific revision of a currency
	// (GET /v1/currencies/{currencyID}/revisions/{revisionNumber})
	GetCurrencyRevision(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, revisionNumber RevisionNumber)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListCurrencies List currencies with pagination
// (GET /v1/currencies/)
func (_ Unimplemented) ListCurrencies(w http.ResponseWriter, r *http.Request, params ListCurrenciesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCurrency Create new currency record
// (POST /v1/currencies/)
func (_ Unimplemented) CreateCurrency(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ExportCurrencies Export currencies in Excel format
// (POST /v1/currencies/export)
func (_ Unimplemented) ExportCurrencies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteCurrency Delete currency record
// (DELETE /v1/currencies/{currencyID})
func (_ Unimplemented) DeleteCurrency(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params DeleteCurrencyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrency Get currency by ID
// (GET /v1/currencies/{currencyID})
func (_ Unimplemented) GetCurrency(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params GetCurrencyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCurrency Update currency information
// (PATCH /v1/currencies/{currencyID})
func (_ Unimplemented) UpdateCurrency(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params UpdateCurrencyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCurrencyRevisions List all revisions for a currency
// (GET /v1/currencies/{currencyID}/revisions)
func (_ Unimplemented) ListCurrencyRevisions(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, params ListCurrencyRevisionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrencyRevision Get specific revision of a currency
// (GET /v1/currencies/{currencyID}/revisions/{revisionNumber})
func (_ Unimplemented) GetCurrencyRevision(w http.ResponseWriter, r *http.Request, currencyID CurrencyID, revisionNumber RevisionNumber) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCurrencies operation middleware
func (siw *ServerInterfaceWrapper) ListCurrencies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCurrenciesParams

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageToken" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageToken", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageToken"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageToken", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "filter"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_by", r.URL.Query(), &params.OrderBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "order_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_by", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "allowDeleted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "allowDeleted", r.URL.Query(), &params.AllowDeleted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "allowDeleted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "allowDeleted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCurrencies(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCurrency operation middleware
func (siw *ServerInterfaceWrapper) CreateCurrency(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCurrency(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportCurrencies operation middleware
func (siw *ServerInterfaceWrapper) ExportCurrencies(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportCurrencies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCurrency operation middleware
func (siw *ServerInterfaceWrapper) DeleteCurrency(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currencyID" -------------
	var currencyID CurrencyID

	err = runtime.BindStyledParameterWithOptions("simple", "currencyID", chi.URLParam(r, "currencyID"), &currencyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currencyID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteCurrencyParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "force", r.URL.Query(), &params.Force, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "force"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCurrency(w, r, currencyID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrency operation middleware
func (siw *ServerInterfaceWrapper) GetCurrency(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currencyID" -------------
	var currencyID CurrencyID

	err = runtime.BindStyledParameterWithOptions("simple", "currencyID", chi.URLParam(r, "currencyID"), &currencyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currencyID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCurrencyParams

	// ------------- Optional query parameter "allowDeleted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "allowDeleted", r.URL.Query(), &params.AllowDeleted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "allowDeleted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "allowDeleted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrency(w, r, currencyID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrency operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrency(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currencyID" -------------
	var currencyID CurrencyID

	err = runtime.BindStyledParameterWithOptions("simple", "currencyID", chi.URLParam(r, "currencyID"), &currencyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currencyID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateCurrencyParams

	// ------------- Optional query parameter "updateMask" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updateMask", r.URL.Query(), &params.UpdateMask, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "updateMask"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updateMask", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrency(w, r, currencyID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCurrencyRevisions operation middleware
func (siw *ServerInterfaceWrapper) ListCurrencyRevisions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currencyID" -------------
	var currencyID CurrencyID

	err = runtime.BindStyledParameterWithOptions("simple", "currencyID", chi.URLParam(r, "currencyID"), &currencyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currencyID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCurrencyRevisionsParams

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageToken" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageToken", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageToken"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageToken", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "filter"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_by", r.URL.Query(), &params.OrderBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "order_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_by", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "allowDeleted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "allowDeleted", r.URL.Query(), &params.AllowDeleted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "allowDeleted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "allowDeleted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCurrencyRevisions(w, r, currencyID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrencyRevision operation middleware
func (siw *ServerInterfaceWrapper) GetCurrencyRevision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currencyID" -------------
	var currencyID CurrencyID

	err = runtime.BindStyledParameterWithOptions("simple", "currencyID", chi.URLParam(r, "currencyID"), &currencyID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currencyID", Err: err})
		return
	}

	// ------------- Path parameter "revisionNumber" -------------
	var revisionNumber RevisionNumber

	err = runtime.BindStyledParameterWithOptions("simple", "revisionNumber", chi.URLParam(r, "revisionNumber"), &revisionNumber, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revisionNumber", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrencyRevision(w, r, currencyID, revisionNumber)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currencies/", wrapper.ListCurrencies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/currencies/", wrapper.CreateCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/currencies/export", wrapper.ExportCurrencies)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/currencies/{currencyID}", wrapper.DeleteCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currencies/{currencyID}", wrapper.GetCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/currencies/{currencyID}", wrapper.UpdateCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currencies/{currencyID}/revisions", wrapper.ListCurrencyRevisions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currencies/{currencyID}/revisions/{revisionNumber}", wrapper.GetCurrencyRevision)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7c9u2lv8qZ7F3pvYu9fAjbqud/OHYba+zaZKJ7du5jb0ORB5JaEiAAUDbikfffecAIEWKlC03yX20",
	"+SuSDIAH5/k7D+aOxSrLlURpDRvdsZxrnqFF7b4dpqm6OcYULSb0PUETa5FboSQbsZMJGLRgFbyzusB3",
	"EXBab0AjT4ScRpCpREzm7qPSIKRFzWMr5BRuhJ2BRqMKHaMBO+MWZvwaYYwoIeP6PSbADST+4f0LySIm",
	"6KkfCtRzFjHJM2QjxuskRszEM8y4p3XCi9Sy0YSnBiNm5zmtHyuVIpdssYjYUaE1ynh+cty+3LkUHwoE",
	"kaC0YiJQg5qAnSHEYRNojJVO+vBzYSyMETjkyggrrtHddIq6RnXO7WxJdLx8cMQ0fiiEJgYTF+tXwFue",
	"5Smy0Xf7w4hNlM64ZSMmpD3YZxHLhBRZkbHRTnW78GB3ux9FalG3b3YoAW9zjcYIJWGiNEzcShKLRlOk",
	"1vThxIIp8lxpa4A0hGthlASVo+ZWaQNbTyP4j6cRXBTD4V4c/sXye/kHfLodQaqmIuZpffPhy+MIXr2J",
	"4OWrs+0IuEwgVtJyITOUFuIZxu8NbGF/2o/gnbHcFgaewgU7PDo7+dsPFwwOXx4DL+xM6T4xFUZwwZ6r",
	"mbxg77bXa4u/KetkMlv3mFyLGMPFYGc4ZBW7jSWueW4rHeMmNkI6REagJNyINCXNmdDeJILxPOfGkBwg",
	"Rk3cgGueioS71bpI0ZAd0Qml6XxjIFXxeyDa8Z57O+oeaR4vhLGv+RRPxceOm70ssrG3CkyRpGYgRw05",
	"n+IaIvLyrE46dofRUhZPhhHL+G1Q7+HwQWUvaT1T71G2iX3Np0J6Nlpa4dReo9UCr4nfxFKJt9aRT3eq",
	"DOHcoPtr2KZV5r7mGq+FKgwtzJWkRQqmaJsnrRdIXtHarYs4f37z91+S9OQ3NX9x9NzwX3by5Ojk4OXZ",
	"s++Z480LlFM7I+7s7jv2VD9E5G0sanrs/73lvY+HvV+Hve+vepf//ZdO3X2lE9TP5h2ugmw/4z2DFBcs",
	"JpAKY4k/RmkLE4FpYvpwaGKU5PFB0UmwxU28DcJAYTCB8RyCkPtwpiCecTn1PE2ERmcJEa10P70jAt6B",
	"KSYTcVs5gLqh04IIrLAp3mfpjpKr8XwNf9ecCNzEnSx6g9eC/KXX+janzmYIBj8UKK3gKcjKOLyx+s0R",
	"mal28c8p0s7vCh66ScpGAWTv8eHjPE+4xZ+5ed++7Y9O8KTyY4TCLUz60NYWz0BiA13BbSB+eL2ppOs4",
	"HwWJjIV6t90HOPGsq/AIqZPKhKVjla6c6n951FEeSf4TExAy8P1DgcRflcyB6yWpa7WmWF66W29Wae1Q",
	"lkXESqfgQNQPWiunMRThUFr6yPM8FbFzSIPfjJKNhxC3LRepYaO3d8zdjI1YrBIkqaEx5GJHrFQdvOWx",
	"TeewB0Weo465QUjROgy3iJYHyFJf7jsiEVNhDVtc1pf9bRmEJlykmLBFnTt/0ThhI/afgyWUHPi/moG/",
	"vGNKU4XcHyrvSQeeFnGMxvwi7KwEZqXVkXffgINLknKtctRWeAkEuBW+Nel4ERxaDdb5ZxpSEYuZeeiK",
	"q8SyRaUTXGs+p+8UEe4JT+5n0ucQkrAZRlgtMrqjrujXKxeSrq55WmCnzwq/qPFvGNsuGQSOT4p0GcYc",
	"MBfSewuSOB+rwnaxpymyH25jTH8UKd4jp2uZ9FWO8jZL/fmmpyYTEWOi4iJDafsmp9zBzBBtlvbdv03B",
	"Vl5sLCR3ltthfm3XPBEpwowbn16Y6t7pHKYo0XsrQqHCZy9zBxASdSNTxZM+i9gMeRKyoiN/u96xMN5p",
	"K9kVOv0OENJYXfish6Q61urGoCZpl+cHp+jCD3AJ3FoezxwSduLgYHKMKQtJgByV91+1YFat/x93DK15",
	"esE0En6/2h3u7vVvU3N7wRpOrcW4VYHmXCaYHDWM58tboMCNLW+FxPkfwPJKfIXhakvDq9kku1dS88fF",
	"GhdXRuz8lHLRWCOZwpUzsd3h7kFvZ9gbPjkbfjt6sj8aDn9ldJNYZJyi027EUm7slYd0mo3Y3oR/92Ry",
	"sN978u3Ot739Jwe7vfHeJO7txt8f7E0ODviEHyyj7fkpHKs05ZpFZXQase/2hw7TBGdK6CSE7Xuo2jwe",
	"tVTmEcJ5QCgVEd5L1KTRPP+oYzdBFh5TQYHLODyONPHk9BXs7+58S8hRJpzqDScyTosEDfA0n/ExWhE7",
	"1yWLDLWIgQRqfJ5JfPbZtVaFR+i5xthx1juRFTN1utDGthqx5yGFL+L4VIqnS0bQTtiqUUQ/bPfhML3h",
	"cyohSCOMNR4Ra8QaVnnBrZAlYll1bV4ta+nOXiPX2WvmOoe9Xy/v9hYdWU5dbbuw+xKwh3WQpzxGA1uZ",
	"kEpDIYU1275aon36Tmu4tga2YpTWRPBe5VS22KakseAUW3YjGBcuJ9ToACjexugeW6HfoTvz+eu/E6rd",
	"c1+e/fV4e4UPu7V0eL8G3Ydt6B4xYa6Ses2umeiv1CdkQr4BDdzMkOjsqnHVIqea2F5Zk6sTuKaKUJr6",
	"KstfUdh3iRIlYKuVNSHhTWGM4JKY8oOcpsLM+it6sXQdLVHLtUkaKbKDuEtrqWtwH+C1zyAoEJfpi1Vk",
	"NQb1NULqS5vwEbWqZPjNd/vDb5zozk9bogsObUMVvrhIuhV4Uc/z3pbZQIXpHZtrSn7ZCkIRawHV9Z6p",
	"dL+lAmicpOgxjHf2BjKeuKJHxcCEW96Hs5kwVPfFtMRSPSXTeb/ta9w5HTSE813YKnM5YeokpdwlylY1",
	"SzFKYgTeo9pShM9PX72E19zGM9h68+MRHHw/3N1uqNLbO6Zyl1Y7i2eRT7dHbBB46sN8XeUWlzWA0mIz",
	"3fmVTOdlOr6KSPzFfTTrckUU65zPtiJDMkufzPptcMMr1jQtYk20rgAzHdujI9laEpcWVNI47ghf5+cn",
	"x6XJFoacpgYzNxYzqAKuL+jnqOnxmNQu0CR6Q7xQXaIoRLIR/UEpr0RX32J9Tb+paWNMlZy6ssWWxgnS",
	"GjTtmNy0gaZ6dZfu11yg7sSTR/QkVsy1QYCvD/4OCspDr+TnrXnVidt7mJAVx+fkXxdvm9BSfVlDjxuG",
	"1+UeqzrNChoMQhYfMQFsVC2Cs6F/XBHq8PWJX2Ha7q4q6bRCYR7AhHMQHoFYV2UJT6uhxD4ccYKKDgD6",
	"mlcvpIZxvVXgiSDD5EkiwvkuJbi1K+HpkytMl5sma0TTsbtaV55WPXWVP38tMi57pCV8nGLgSVgNfunY",
	"dRTJ49y4nFkrOW36mXYF66EAW9KzVlPCVVr0HpfSaxdRqjw+DtdQui41YUyBbc0J4rnrLGtg6ksC3uHG",
	"3FXcyf78A7bEBEL+N06x6ZlKebec51pRnDapL4UwcT0pYQI5VDhxPGg+bRNl2iCXjlhXuvs1wfrnJ1j1",
	"2sFjcM1KrkEAR0hBISWdQzi0BXX2esOd3nDnbDgcDYf3QZ0/cR4Y8rTPIZBG3gcvizQFUcZ5t0gY19S+",
	"xv46QcgiTckJrcVs/1Jpa7Ou9bkgcEok28+JhNu579d8+7Pk2/US5KOAb5BxubvKY122KkzFgFUc3Lbf",
	"etnzE+2X1Lnqfv7utPHTShI1jq7YVyN2NO7dRl9UZMW40MLOTwlZ+rj6vziPU8Xfvzos7Gy3oxtT2BlJ",
	"y5fB4VpwKLfAltsEu/0hDOBVjvLkGI6UlBjb7aCgjq/PfzkjBIH01XUNQpf50DWDxUd/dOj6bD1DrlGH",
	"qSG33n3EoK4TGpQjOnl991GAB40fz3XKRmxmbW5Gg8H7QHZ/rgrdS1TGhezHKhto5GlmBvTzlfs8yLWy",
	"KlbpQOUoRdKL/aUGdLrrBKl8tTsz8k6SJmZQZ1yiJKjmf1xVLMOi+k68zZW21Nl1H2rtHFJ91x4M+VJz",
	"HyF7NmJvkK/k0R5WlWY0E8Yq1/Cr7b3RwhF75NTHbfDK06aVkCRJ4bNz051Kx8epQGmPNCbeLxjfEPvK",
	"5M/H5Fo6wJ2hu+4NofwOk6dkXCa5EtIaFywqclMxwXgepwgZl3zqptdCchDiT5kVkK90Ix+OeaECBD+7",
	"XRqqPOPw9QkVClH7eMF2+sP+kLhB1+C5oPje3+kPQ3HR6cPgemew5PKAfpr6brefkxRKniShPXpUb43W",
	"R3TfdufcyyWDxhDfItp4/VlQ6wc3hDHTDVaWY2YbLG0MHlOJoTFRszscrqs2VOsG97eyFxHb3+SUML9C",
	"q3cetXrvEaufPIqSJ488e3/j1RRbiyzjel625Wv+xWXMeTVHSWfnynRAk9JPgMSbFhjZPAs/q0OZclI2",
	"4AS/sXJbAYDt+AkOnztChpa7loSLt02b8iSW5htG6NDYZyr5lO55ozP+UI9745Z1s1XdHPZbtCxj51Ms",
	"Y/6vZRf7w+//Ta0oIFTnoFex6dt2cL1cXNZNL1hQh/2401ciR4kJ7tbY409hwMmEWG8LLelzCRdEiuXw",
	"fTmjlHaN5DRNyAOQRmD6RB9dzo99dc2fqlRBI1a0qg0ZhWxCxg7lulu+qrLwquWha2vAvo1kecv5V9Pz",
	"vlYSmsXhZYiYS6lchbiQiZJIpc0UuDEqFs7nr6JUHxR4atwUssZMXZejvU1V9Tii5u0fh6BqbwltAofc",
	"mxYdkGX/D+WY9//oNhQUfcWGjjuTNCIkYPemVbwphwqTjZpC1bHjOQhroFjt9/bhTXDfy0KP9e/+dBT1",
	"qIvhX+paMZz7oNFPaP9BlvJFMf5Xg/nc+cBPaBsK6oTMchqt6XrfSocGzmqpoNHNpr4/5FpdC5qqDO9w",
	"lFi/9l4JIaFKiztzgeWAyXI8pkO7/Ust/yAFr71Bs7h8bI7xJXKDP69F/VkzifP11vcQ2hss3/RYlqbW",
	"hDdnfYpyYovtcOPGY9pRbhnMaHamehqh0nimlVTVe8M6QR2BmambatCjtPUb1OhGEaOqATKv/0gpz3gO",
	"NzOVdfmDWnGtGos0X9gtfK3IrXnB62vE/gIVvKZteVOMl1FjQxcwuGu+dbp42CdsBnkrZ6EmNcL6cDqj",
	"/0iC/IqbF1qDcXnoslenuGq/74luBghqcPfNsjv5Jc1/5U3ir6b07wJ+H9BZtnhcvHYtucvF5eL/BwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
