// Package currencyv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package currencyv1

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCurrencies List currencies
	// (GET /v1/currency)
	ListCurrencies(w http.ResponseWriter, r *http.Request, params ListCurrenciesParams)
	// CreateCurrency Create a new currency
	// (POST /v1/currency)
	CreateCurrency(w http.ResponseWriter, r *http.Request)
	// DeleteCurrency Delete currency
	// (DELETE /v1/currency/{currency_id})
	DeleteCurrency(w http.ResponseWriter, r *http.Request, currencyId int64)
	// GetCurrency Get currency
	// (GET /v1/currency/{currency_id})
	GetCurrency(w http.ResponseWriter, r *http.Request, currencyId int64)
	// UpdateCurrency Update currency
	// (PATCH /v1/currency/{currency_id})
	UpdateCurrency(w http.ResponseWriter, r *http.Request, currencyId int64, params UpdateCurrencyParams)
	// ListCurrencyRevisions List currency revisions
	// (GET /v1/currency/{currency_id}/revisions)
	ListCurrencyRevisions(w http.ResponseWriter, r *http.Request, currencyId int64, params ListCurrencyRevisionsParams)
	// GetCurrencyRevision Get specific revision
	// (GET /v1/currency/{currency_id}/revisions/{revision_number})
	GetCurrencyRevision(w http.ResponseWriter, r *http.Request, currencyId int64, revisionNumber int32)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListCurrencies List currencies
// (GET /v1/currency)
func (_ Unimplemented) ListCurrencies(w http.ResponseWriter, r *http.Request, params ListCurrenciesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCurrency Create a new currency
// (POST /v1/currency)
func (_ Unimplemented) CreateCurrency(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteCurrency Delete currency
// (DELETE /v1/currency/{currency_id})
func (_ Unimplemented) DeleteCurrency(w http.ResponseWriter, r *http.Request, currencyId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrency Get currency
// (GET /v1/currency/{currency_id})
func (_ Unimplemented) GetCurrency(w http.ResponseWriter, r *http.Request, currencyId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCurrency Update currency
// (PATCH /v1/currency/{currency_id})
func (_ Unimplemented) UpdateCurrency(w http.ResponseWriter, r *http.Request, currencyId int64, params UpdateCurrencyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCurrencyRevisions List currency revisions
// (GET /v1/currency/{currency_id}/revisions)
func (_ Unimplemented) ListCurrencyRevisions(w http.ResponseWriter, r *http.Request, currencyId int64, params ListCurrencyRevisionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrencyRevision Get specific revision
// (GET /v1/currency/{currency_id}/revisions/{revision_number})
func (_ Unimplemented) GetCurrencyRevision(w http.ResponseWriter, r *http.Request, currencyId int64, revisionNumber int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCurrencies operation middleware
func (siw *ServerInterfaceWrapper) ListCurrencies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCurrenciesParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCurrencies(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCurrency operation middleware
func (siw *ServerInterfaceWrapper) CreateCurrency(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCurrency(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCurrency operation middleware
func (siw *ServerInterfaceWrapper) DeleteCurrency(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currency_id" -------------
	var currencyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "currency_id", chi.URLParam(r, "currency_id"), &currencyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCurrency(w, r, currencyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrency operation middleware
func (siw *ServerInterfaceWrapper) GetCurrency(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currency_id" -------------
	var currencyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "currency_id", chi.URLParam(r, "currency_id"), &currencyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrency(w, r, currencyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrency operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrency(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currency_id" -------------
	var currencyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "currency_id", chi.URLParam(r, "currency_id"), &currencyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateCurrencyParams

	// ------------- Required query parameter "update_mask" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "update_mask", r.URL.Query(), &params.UpdateMask, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "update_mask"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "update_mask", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrency(w, r, currencyId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCurrencyRevisions operation middleware
func (siw *ServerInterfaceWrapper) ListCurrencyRevisions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currency_id" -------------
	var currencyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "currency_id", chi.URLParam(r, "currency_id"), &currencyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCurrencyRevisionsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCurrencyRevisions(w, r, currencyId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrencyRevision operation middleware
func (siw *ServerInterfaceWrapper) GetCurrencyRevision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "currency_id" -------------
	var currencyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "currency_id", chi.URLParam(r, "currency_id"), &currencyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "currency_id", Err: err})
		return
	}

	// ------------- Path parameter "revision_number" -------------
	var revisionNumber int32

	err = runtime.BindStyledParameterWithOptions("simple", "revision_number", chi.URLParam(r, "revision_number"), &revisionNumber, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revision_number", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrencyRevision(w, r, currencyId, revisionNumber)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currency", wrapper.ListCurrencies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/currency", wrapper.CreateCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/currency/{currency_id}", wrapper.DeleteCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currency/{currency_id}", wrapper.GetCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/currency/{currency_id}", wrapper.UpdateCurrency)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currency/{currency_id}/revisions", wrapper.ListCurrencyRevisions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/currency/{currency_id}/revisions/{revision_number}", wrapper.GetCurrencyRevision)
	})

	return r
}
